apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-cmdargs
  name: kplabs-cmdargs
spec:
  containers:
  - image: busybox
    name: kplabs-cmdargs
    command: ["sleep"] 
    args: ["3600"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
