apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kplabs-config
  name: kplabs-config
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kplabs-config
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kplabs-config
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}
